seed_everything: null
trainer:
  precision: 16-mixed
  max_epochs: 20
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./lightning_logs
      name: 1-transformer-256-c128-b128-rmsn-pos
  callbacks:
    - class_path: lm.model.DummyCallback
    - class_path: lm.model.TorchScriptCallback
      init_args:
        config:
          batch_size: &batch_size 64
          seq_len: &seq_len 384
          vocab_size: &vocab_size 215
          save_every_epoch: 5


model:
  class_path: lm.model.Seq2SeqLM
  init_args:
    model:
      class_path: lm.module.TransformerLM
      init_args:
        config:
          vocab_size: *vocab_size
          seq_len: *seq_len
          embed_dim: 512
          num_heads: 8
          num_layers: 6
          batch_first: true
          norm_first: true
          dropout_ratio: 0.05
          use_position_embedding: false
    loss:
      class_path: torch.nn.CrossEntropyLoss
    vocab_size: *vocab_size
    
data:
  class_path: lm.data_module.InMemoryDataModule
  init_args:
    config:
      data_path: ./data/
      samples_per_epoch: 10000
      batch_size: *batch_size
      seq_len: *seq_len
      token_file_path: ./data/tokens.json

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0005
    weight_decay: 0.01

lr_scheduler:
      class_path: torch.optim.lr_scheduler.StepLR
      init_args:
        step_size: 10
        gamma: 0.9
        verbose: True